### ISSUE TITLE
_validateModel needs to be static method

### ISSUE THREAD

**Issue by maplealmond** [Cerapter/pf2e-heroic-crafting-automation#15]
```commons.js:2070 Error: AddCraftProgressRuleElement defines AddCraftProgressRuleElement.prototype._validateModel instance method which should now be declared as AddCraftProgressRuleElement.validateJoint static method.
Backwards-compatible support will be removed in Version 13
    at Object.logCompatibilityWarning (commons.js:2059:19)
    at AddCraftProgressRuleElement.validateJoint (commons.js:7222:23)
    at AddCraftProgressRuleElement.validate (commons.js:7173:28)
    at AddCraftProgressRuleElement.validate (pf2e.mjs:1354:139900)
    at new DataModel (commons.js:6918:12)
    at new RuleElementPF2e (pf2e.mjs:1354:137404)
    at new AddCraftProgressRuleElement (add-craft-progress.js:7:9)
    at pf2e.mjs:1605:141470
    at RuleElements.fromOwnedItem (pf2e.mjs:1605:141712)
    at FeatPF2e.prepareRuleElements (pf2e.mjs:1621:326866)
```

This console error (or possibly some others) seem to break the REs.

**Comment by Cerapter** [comment]
Fixed as of 4.0.
